export const INITIAL_LOADING = 'INITIAL_LOADING';

export const GET_QUESTION_DECK = 'GET_QUESTION_DECK';
export const DELETE_QUESTION_DECK = 'DELETE_QUESTION_DECK';
export const DELETE_QUESTION_DECK_SUCCESS = 'DELETE_QUESTION_DECK_SUCCESS';
export const DELETE_QUESTION_DECK_FAIL = 'DELETE_QUESTION_DECK_FAIL';
export const ADD_QUESTION_DECK = 'ADD_QUESTION_DECK';
export const ADD_QUESTION_DECK_SUCCESS = 'ADD_QUESTION_DECK_SUCCESS';
export const UPDATE_QUESTION_DECK_CARD = 'UPDATE_QUESTION_DECK_CARD';

export const GET_QUESTION_CARD = 'GET_QUESTION_CARD';
export const ADD_QUESTION_CARD = 'ADD_QUESTION_CARD';
export const ADD_QUESTION_CARD_SUCCESS = 'ADD_QUESTION_CARD_SUCCESS';
